version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8000:8000'
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/sc-test
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
